var GAME_LEVELS = [
  ["                                                                                ",
   " @                                                                              ",
   " xxxxxxxxxxxxyy                                                                 ",
   " yyyyyyyyyyyyyyt                                                   = = =      o ",
   " yyyyyyyyyyyy                                    yyyyyyyyyyyyyyyyyyyyyyyyyyyyyy ",
   " yyyyyyyyy               yyyxxxxxxxxxxxxxyy       !!!!!!!!!!!!!!!!!!!!!!!!!!!!! ",
   " !!!!!!!!                     yyyyyyyyyyyyyyy                                   ",
   " ! p         yyy              yyyyyyyyy                                         ",
   " !      =          yyyyyyy                                                      ",
   " !xxxxxxxxxx!!!!!                             yxxxxy                       o    ",
   " !!!!!!!!!!!!!                                 yyyy                     yyyyyyyy",
   "                                                  yyyyyy                  yyyyyy",
   "                        xxxxxxxxxxxx                                         yyy",
   "                      yyyyyyyyyyyyyyyy                         xxxxx            ",
   "     o                    yyyyyyyyyy                           yyyyyyy          ",
   " yyyyyyyyyyyyy                                                  yyyy            ",
   " yyyyyyyyyyyyyy                                                                 ",
   " yy   !!!!!|                                                          xxxxxxxxxx",
   " yy                 xxxx                      o                          yyyyyyy",
   " yy    o           yyyyyy     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                   ",
   " yy                        yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyt                  ",
   " yyyyyyyyyyyyyyy        yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy      yyy",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                                                "],
  ["                                                                                                                                               ",
   "                                                                                                                                               ",
   "                                                                                                                                               ",
   "                                                                                                                                               ",
   "                                                                                                                                               ",
   "                                                                                                                                               ",
   "                                                                                                                                               ",
   "                                                                                                                                               ",
   "                                                                                                                                               ",
   "                                                                                                                                               ",
   "                                                                                                                                               ",
   " yyyyyyyyyyyyyyyy                                                                                                                              ",
   "                                                                                                                                               ",
   "                                                                                                                                               ",
   "                                                                                                                                               ",
   "                                                                                                                                               ",
   "                                                                                                                                               ",
   "          yyyyyyyyy        yyyyyyyyy                                                                                                           ",
   "           yxxxxxxxy       yxxxxxxy                                                                                                            ",
   "            yx     xy     yx    xy                                                                           yyyyyy                            ",
   "             yx     xy   yx    xy                                                                            yxxxxy                            ",
   "              yx     xy yx    xy                                                                                                               ",
   "               yx     xyx    xy       yyyy      yyyyyy    yyyyyy    yyyyyy         y     y          yyyyyy   yyyyyy   yyyyyy   yyyyyyy         ",
   "                yx     x    xy       yxxxxy     yxxxxy    yxxxxy     yxxxy        y   p   y        yxxxxy    yxxxxy   yxxxxy  yxxxxxxy         ",
   "                 yx        xy       yx    xy    yx  xy    yx  xy      yx  xy     yx  xyx  xy      yx  xy     yx  xy   yx  xy yx     xy         ",
   "                 yx        xy      yx      xy   yx  xy    yx  xy       yx  xy   yx  xy yx  xy    yx  xy      yx  xy   yx  xyx  x    xy         ",
   "                 yx        xy     yx        xy  yx  xy    yx  xy        yx  xy yx  xy   yx  xy  yx  xy       yx  xy   yx   x  xyx   xy         ",
   "                 yx        xy      yx      xy   yx  xy    yx  xy         yx  xyx  xy     yx  xyx   xy        yx  xy   yx     xy yx  xy         ",
   "                 tx        xy       yx    xy    yx  xyyyyyyx  xy          yx  x  xy       yx  x   xy         yx  xy   yx    xy  yx  xy         ",
   "                 yxxxxxxxxxxy        yxxxxy      yxxxxxxxxxxxxy            yxxxxxy         yxxxxxxy          yxxxxy   yxxxxxy   yxxxxy         ",
   "                 yyyyyyyyyyyy         yyyy        yyyyyyyyyyyy              yyyyy           yyyyy            yyyyyy   yyyyyy    yyyyyy         ",
   "                                                                                                                                               ",
   " @                                                                                  o                                                          ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["   yyyyyyyyyyyyy                                                             yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
   "   yyyyyyyyyyyy                                                                         |                 =     yy",
   "                                                                                                            o   yy",
   "     o                                  xxxxxxxxxxxxx                   !!xxxxxxx!!       t              yyyy   yy",
   "yyyyyyyyyyyyyyyyy                      yyyyyyyyyyyyyyy               yyyyyyyyyyyyyyy       yyyyyyyyyyyyyyyyyyyyyyy",
   "       |         t                       yyyyyyyyyyyy                                        yyyyyyyyyyyyyyyyyyyyy",
   "                                                                                                                  ",
   "                                               xxxxxxxxxxxxt                                                      ",
   "                  xxxxxxxxxxxxxxxxxxx        yyyyyyyyyyyyyyyy               xxxxxxxxxxxxt               xxxxxxxxxx",
   "                 yyyyyyyyyyyyyyyyyyyyy         yyyyyyyyyyyy                  yyyyyyyyyyyyy            yyyyyyyyyyyy",
   " @                                                                           yyyyyyyyyyyyyyy                      ",
   "yxxxxxxxxxxxxxxyt                                               xxxxxxxx                                          ",
   "yyyyyyyyyyyyyyyyy                                              yyyyyyyyyy                    xxxxxxxxxxxxx        ",
   "yyyyyyyyyyyyyyy                       xxxxxxxxxxxxxxxx           yyyyyy                    yyyyyyyyyyyyyyyyy      ",
   "yyyyyyyyyyyyy                        yyyyyyyyyyyyyyyyyy                    xxxxxxxxxx        xxxxxxxxxx           ",
   "                                                                          yyyyyyyyyyyy                            ",
   "                                                                            yyyyyyyy            xxxxxxx           ",
   "                           yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy                              yyyyyyyyyy          ",
   "                      yyyyyy                                                                                  xxxx",
   "yy       yyyyyyyyyyyyyyyyy                                                                                   yyyyy",
   "yy       yyyyyyyyyyyyyyyyy                                                                                    !!!!",
   "yy                                        yyyyyyyyyyyyyyyyyyyyyyyyyt                                              ",
   "yy                              yyyyyyyyyyyyy!!!!!!!|t          !!!!!yyyyyyyyyyyyyyyyy                            ",
   "yyy    yyyyyyyyyyy         yyyyyyyyyyyyyyyyyy                      yyyyyyyyyyyyyyyyyyyy                  xxxxx    ",
   "y |    yyyyyyyyyyyy         yyyyyyyyyyyyyyyyyy      p               yyyyyyyyyyyyyyyyyyyy              xxxxxx      ",
   "                           yyyyyyyyyyyyyyyyyyyyyyyyyyyyy          yyyyyyyyyyyyyyyyyyyyyyy         xxxxx           ",
   "  o                                                                                             xx             xxx",
   "                  =                           =                               =                              p    ",
   "xxxxxxx         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    xxxxxxttttxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                                                               ",
   "                                                                                                                                               ",
   "                                                                                                                                               ",
   "                                                                                                                                               ",
   "                                                                                                                                               ",
   "                                                                                                                                               ",
   "                                                                                                                                               ",
   "                                                                                                                                               ",
   "                                                                                                                                               ",
   "                                                                                                                                               ",
   "                                                                                                                                               ",
   "                                                                                                                                               ",
   "yyyyyyyyy                                                                                                                                      ",
   "                                                                                                                                               ",
   "                                                                                                                                               ",
   "                                                                                                                                               ",
   "            p                                                                                                                                  ",
   "          yyyyyyyyy        yyyyyyyyy                                                                                                           ",
   "           yxxxxxxxy       yxxxxxxy                                                                                                            ",
   "            yx     xy     yx    xy                                                                           yyyyyy                            ",
   "             yx     xy   yx    xy                                                                            yxxxxy                            ",
   "              yx     xy yx    xy                                                                                                               ",
   "               yx     xyx    xy       yyyy      yyyyyy    yyyyyy    yyyyyy         yyyyyy           yyyyyy   yyyyyy   yyyyyy   yyyyyyy         ",
   "                yx     x    xy       yxxxxy     yxxxxy    yxxxxy     yxxxy        yxxxxxx y        yxxxxy    yxxxxy   yxxxxy  yxxxxxxy         ",
   "                 yx        xy       yx    xy    yx  xy    yx  xy      yx  xy     yx  xyx  xy      yx  xy     yx  xy   yx  xy yx     xy         ",
   "                 yx        xy      yx      xy   yx  xy    yx  xy       yx  xy   yx  xy yx  xy    yx  xy      yx  xy   yx  xyx  x    xy         ",
   "                 yx        xy     yx        xy  yx  xy    yx  xy        yx  xy yx  xy   yx  xy  yx  xy       yx  xy   yx   x  xyx   xy         ",
   "                 yx        xy      yx      xy   yx  xy    yx  xy         yx  xyx  xy     yx  xyx   xy        yx  xy   yx     xy yx  xy         ",
   "                 yx        xy       yx    xy    yx  xyyyyyyx  xy          yx  x  xy       yx  x   xy         yx  xy   yx    xy  yx  xy         ",
   "                 yxxxxxxxxxxy        yxxxxy      yxxxxxxxxxxxxy            yxxxxxy         yxxxxxxy          yxxxxy   yxxxxxy   yxxxxy         ",
   "                 yyyyyyyyyyyy         yyyy        yyyyyyyyyyyy              yyyyy           yyyyy            yyyyyy   yyyyyy    yyyyyy         ",
   "                                                                                                                                               ",
   " @                                                                                  o                                                       t  ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["    yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy                                                         |                 ",
   "!  |     ! =                                          o                                                       ",
   "!   p                                        yyyyyyyyyyt                                                      ",
   "yxxxxx                                                                                                        ",
   "y!!!!!!yyy                        yyyyyyyyyy                                                                  ",
   "yyyyyyyyyy          yyyyyyyyy                                                                                 ",
   "yyy              yyyyyy                                                                                       ",
   "  yyyyy        yyyy                      xt                                       xy                          ",
   "      yyyyy                              x  y                                     x  y                        ",
   "        yyyyyy          yyyyyyyy         x     y                                  x    y                      ",
   "           yyyyy     yyyy                x o     y                                x o    y                    ",
   "                   yyyy                  xyyy   yyyy                              xyy      y                  ",
   "            y                          xxxxx                                    xxxxx                         ",
   "            y                        xxxxxxxxx                                xxxxxxxxx                       ",
   "            y  o          y        xxxxxxxxxxxxx                            xxxxxxxxxxxxx                     ",
   "            yyyyyyyyy     y           xx   xx        yyyyyyyyyyy               xx   xx        yyyyyyyyy       ",
   "                          y           xxo  xx         yyyyyyyyy                xx   xx         yyyyyyy        ",
   "            y             y           xxx  xx           yyyyy                  xx   xx          yyyyy         ",
   "            y       yyyyyyy           xx   xx       =                          xx   xxxxxx       yyy          ",
   "            y                         xx  xxxxxxxxxxxxxxxxxxxxxxx       xxxxxxxxx   xx         yyyy           ",
   "            y =            y          xx   xx           |        x       x     xx   xx                        ",
   "            yyyyyyyy      y           xx   xx                   xxxx     x     xx   xx                        ",
   "                          y           xxx  xx                            x     xx   xxxxxxxxx         yyyyy   ",
   "                          y           xx   xx                            x     xx   xx                 yyy    ",
   "                          y           xx   xxxxxxxx           xxxxxxxxxxxx     xx   xx                        ",
   "                 yyyyyyyyyy           xx  xxxxxxxxxxxt                      o  xx   xx        yyyyyyyy        ",
   "                                      xx   xxxxxxxxxxxxxx                   xxxxx   xx         yyyyyy         ",
   "       yyyyyy                         xx                        xxxxxxxx            xx          yyyy          ",
   "        yyyy                        vvxx                      xxxxxxxxxxxx          xxvv                      ",
   "         yy         yyyyy          xxxxxxxxt                xxxxxxxxxxxxxxxx    xxxxxxxxx                     ",
   "                     yyy          xxxxxxxxxx              xxxxxxxxxxxxxxxxxx      xxxxxxxx            yyyyy   ",
   "          yyyyy       y          xx   |          xxxxxxxxxxxxxxxxxxxxxxxxxxxxx            x                   ",
   " @         tyy                  xx            xxx                                           x               o ",
   "xxxxx       y                   xxo                                                          x            xxxx",
   "xxxxx                           xxx       xxxxxxxxxxx                   xxxxxxtxxxxxxxxxxxxxxx            xxxx",
   "xxx            yy               xxx!!!!!xxxxxxxxxxx                   xxxxxxxxxxxxxxxxxxxxxxxx       yyy   xxx",
   "xxx            y      xxxxxx    xxxx!!!!x                                                    x             xxx",
   "xxx     yyyyy         xxxx      xxxxxxxxx                yyyyyyyyyyyy        xxxxxxxxxxx     xyyyyyy       xxx",
   "xxx      yyy          xxxx      x                      yyyyyyyyyyyyyyyyy         xxxxxxxx    xyyyyy        xxx",
   "xxx       y           xxxxxx     x                    yyyyyyyyyyyyyyyyyyyyy                 xyyyyy         xxx",
   "xxx                   xxxx                      vv                                                   =     xxx",
   "xxx          yyyy     xxxx                     xxxx                                               yyyyyyyyyxxx",
   "xxx           yy      xxxxxxxxxxxx           xxxxxxxxx                      xxxxxxxxx              yyyyyyyyxxx",
   "xxx                o  xxxx                xxxxxxxxxxxxxxx      !!!!!!!!!!!!!!!!xxxxxxxxxxxxx         yyyyyyxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxx   xxxxxxxxxxxxxxt                   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!          =   p  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!ttxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                                                               ",
   "                                                                                                                                               ",
   "                                                                                                                                               ",
   "                                                                                                                                               ",
   "                                                                                                                                               ",
   "                                                                                                                                               ",
   "                                                                                                                                               ",
   "                                                                                                                                               ",
   "                                                                                                                                               ",
   " yyyyyy                                                                                                                                        ",
   "            yyyyyyyy                                                                                                                           ",
   "                           yyyyyyy       yyyyyyy     yyyyyy      yyyyyy      yyyyyyy       yyyyyy        yyyyyyy    yyyyyy    yyyyyy           ",
   "                                                                                                                                               ",
   "                                                                                                                                               ",
   "                                                                                                                                               ",
   "                                                                                                                                               ",
   "                                                                                                                                               ",
   "          ppppppppp        pppppppppp                                                                                                          ",
   "           ppppppppp       ppppppppp                                                                                                           ",
   "            pp     pp     pp    pp                                                   yyyyy                   pppppp     yyyyyyy                ",
   "             pp     pp   pp    pp                     yyyy                                                   pppppp                            ",
   "     yyyyy    pp     pp ppyyyypp                                                                                                               ",
   "               pp     ppp    pp       pppp      pppppp    pppppp    pppppp          pppppp         ppppppp   pppppp   pppppp   ppppppp         ",
   "                pp     p    pp       pppppp     pppppp    pppppp     pppppp        pppppppp        pppppp    pppppp   pppppp  pppppppp         ",
   "                 pp        pp       pp    pp    pp  pp    pp  pp      pp  pp     pp  ppp  pp      pp  pp     pp  pp   pp  pp pp     pp         ",
   "                 pp        pp      pp      pp   pp  pp    pp  pp       pp  pp   pp  pp pp  pp    pp  pp      pp  pp   pp  ppp  p    pp         ",
   "                 pp        pp     pp        pp  pp  pp    pp  pp        pp  pp pp  pp   pp  pp  pp  pp       pp  pp   pp   p  ppp   pp         ",
   "                 pp        pp      pp      pp   pp  pp    pp  pp         pp  ppp  pp     pp  ppp   pp        pp  pp   pp     pp pp  pp         ",
   "                 pp        pp       pp    pp    pp  pppppppp  pp          pp  p  pp       pp  p   pp         pp  pp   pp    pp  pp  pp         ",
   "                 pppppppppppp        pppppp      pppppppppppppp            ppppppp         pppppppp          pppppp   ppppppp   pppppp         ",
   "                 pppppppppppp         pppp        pppppppppppp              ppppp           pppppp           pppppp   pppppp    pppppp         ",
   "                                                                                                                                               ",
   " t  @                                                                               o                                                       t  ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
